### ISSUE TITLE
Problem with start time

### ISSUE THREAD

**Issue by MEVAJU** [janar153/node-wall-calendar#1]
Hello there,

I'm trying to use your app as Docker but, after set it up and run, everytime I click on submit button, event starts with the "power on" time of the docker.

I mean: if docker runs at 8:00 and I reserve the room for 15min at 12:20, reservation takes from 8:00 to 8:15.

Any idea about whats I'm doing wrong?

**Comment by MEVAJU** [comment]
We got it working!

We add a new instace of EWS in onclick event in src/app.ts file line 233:
`
const ewsHelper = new EWSHelper();
`

With this as result:

  app.post("/book", (req, res) => {
    i18n.setLocale(req, appLang);
    const minutesToAdd = req.body.meeting_length;
    const ewsHelper = new EWSHelper();
    ewsHelper.addEvent(minutesToAdd).then((result: any) => {
      res.json(result);

**Comment by janar153** [comment]
Thank you for the information. I have added this change to master code also and found that some rows down, there was same issue also.
